### ISSUE TITLE
feature request: SQL prettifier

### ISSUE THREAD

**Issue by tanho63** [stla/prettifyAddins#1]
Hiya, this package looks fantastic 🌟 

I noticed you had license notes from sql-formatter but I didn't seem to see a SQL prettifier addin/function on quick skim - is that in the plans? Would be super useful for my rmarkdown notebooks that call SQL as an engine!

**Comment by stla** [comment]
Hello,

 There is one SQL formatter in *Indent (PhantomJS)*. But there is a better one in *Prettify (V8)* and *Prettify (Shiny)* (these two ones are the same).
